name: Deploy to Raspberry Pi (No Git used)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug environment
      shell: powershell
      run: |
        echo "USERNAME: $env:USERNAME"
        echo "USERPROFILE: $env:USERPROFILE"
        echo "Trying icacls version..."
        icacls /?

    - name: Set up SSH key
      shell: powershell
      run: |
        $keyPath = "$env:GITHUB_WORKSPACE\.ssh"
        mkdir $keyPath -Force
        Set-Content -Path "$keyPath\id_ed25519" -Value "${{ secrets.SSH_PRIVATE_KEY }}" -NoNewline

    - name: Deploy files with rsync
      shell: powershell
      run: |
       wsl rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -i /mnt/c/Users/sjarv/workspace/.ssh/id_ed25519" ./ pi@100.101.255.110:/home/pi/pi-server/

    - name: Restart server on Raspberry Pi
      shell: powershell
      run: |
        ssh -o StrictHostKeyChecking=no -i $env:USERPROFILE\.ssh\id_ed25519 pi@100.101.255.110 `
          "sudo systemctl restart pi-server"
