name: Deploy to Raspberry Pi (No Git used)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug environment
      shell: powershell
      run: |
        echo "USERNAME: $env:USERNAME"
        echo "USERPROFILE: $env:USERPROFILE"
        echo "Trying icacls version..."
        icacls /?

    - name: Set up SSH key
      shell: powershell
      run: |
        $sshPath = "$env:GITHUB_WORKSPACE\.ssh"
        mkdir $sshPath -Force
        Set-Content -Path "$sshPath\id_ed25519" -Value "${{ secrets.SSH_PRIVATE_KEY }}" -NoNewline
        # Optionally set permissions in Windows to be restrictive
        icacls $sshPath\id_ed25519 /inheritance:r
        icacls $sshPath\id_ed25519 /grant:r "$($env:USERNAME):(R)"

    - name: Deploy files with rsync
      shell: powershell
      run: |
        wsl rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -i /mnt/c/actions-runner/_work/pi-server/pi-server/.ssh/id_ed25519" ./ pi@100.101.255.110:/home/pi/pi-server/

    - name: Restart server on Raspberry Pi
      shell: powershell
      run: |
        wsl ssh -o StrictHostKeyChecking=no -i /mnt/c/actions-runner/_work/pi-server/pi-server/.ssh/id_ed25519 pi@100.101.255.110 "sudo systemctl restart pi-server"
