name: Deploy to Raspberry Pi (No Git)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Allow PowerShell script execution (session only)
      run: Set-ExecutionPolicy RemoteSigned -Scope Process -Force
      shell: powershell
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PI_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Deploy files with rsync
      run: |
        rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519" \
          ./ sjarv@100.101.255.110:/home/pi/pi-server/

    - name: Restart server on Pi
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 pi@<your-pi-ip> \
          "sudo systemctl restart pi-server"
